default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_API_KEY"]
    )


    build_app(
      scheme: "CICD",
      export_method: "app-store"
    )

    upload_to_testflight(
      username: ENV["APPLE_ID"]
    )
  end
end

